---
title: "RPeer-graded Assignment: Prediction Assignment Writeup"
author: "Veronica S.Jamilat"
date: "May 26, 2017"
output: html_document
---
## Introduction
This report is prepared as one of the requirement in Practical Machine Learning online course by Johns Hopkins University.
The basic goal of this assignment is to predict the manner of the subject (6 participants) performed some exercise. For this assignment, in order to predict the manner of the subject did the exercise decision tree and random forest method will be performed to determine the best prediction.  The best prediction is determined by the highest accuracy.

## Background
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement ??? a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website [**here**](http://groupware.les.inf.puc-rio.br/har)

##Data
The training data for this project are available [**here**](https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv)

The test data are available [**here**](https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv)

The data for this project come from [**this**](http://groupware.les.inf.puc-rio.br/har) source. 


## Pre-processing
This segment includes packages required and uploading data into r.

Packages needed to perform bagging, random forest and boosting are as follows:
```{r}
ECHO=TRUE

library(e1071)
library(caret)
library(rpart)
library(rpart.plot)
library(rattle)
library(randomForest)
library(corrplot)


#locate downloaded dataset
testing<-read.csv(file="pml-testing.csv",head=TRUE,sep=",")
training<-read.csv(file="pml-training.csv",head=TRUE,sep=",")

## Data processing
# create a partition using caret with the training dataset on 70,30 ratio
inTrain  <- createDataPartition(training$classe, p=0.7, list=FALSE)
TrainSet <- training[inTrain, ]
TestSet  <- training[-inTrain, ]
dim(TrainSet)
dim(TestSet)

# remove variables with Nearly Zero Variance
n0var <- nearZeroVar(TrainSet)
TrainSet <- TrainSet[, -n0var]
TestSet  <- TestSet[, -n0var]
dim(TrainSet)
dim(TestSet)

# remove variables that are mostly NA
AllNA <- sapply(TrainSet, function(x) mean(is.na(x))) > 0.95
TrainSet <- TrainSet[, AllNA==FALSE]
TestSet <- TestSet[, AllNA==FALSE]
dim(TrainSet)
dim(TestSet)

# remove identification only variables (columns 1 to 5)
TrainSet <- TrainSet[, -(1:5)]
TestSet  <- TestSet[, -(1:5)]
dim(TrainSet)
dim(TestSet)

#check correlation among variables
M <- cor(TrainSet[, -54])
corrplot(M, method="circle")

#1.random forest method
# model fit
set.seed(3408)
controlRF <- trainControl(method="cv", number=3, verboseIter=FALSE)
modFitRandForest <- train(classe ~ ., data=TrainSet, method="rf",
                          trControl=controlRF)
modFitRandForest$finalModel

# prediction on Test dataset
predictRandForest <- predict(modFitRandForest, newdata=TestSet)
confMatRandForest <- confusionMatrix(predictRandForest, TestSet$classe)
confMatRandForest

# plot matrix results
plot(confMatRandForest$table, col = confMatRandForest$byClass, 
     main = paste("Random Forest - Accuracy =",
                  round(confMatRandForest$overall['Accuracy'], 4)))

#2.Decision tree
# model fit
set.seed(3408)
modFitDecTree <- rpart(classe ~ ., data=TrainSet, method="class")
fancyRpartPlot(modFitDecTree)

# prediction on Test dataset
predictDecTree <- predict(modFitDecTree, newdata=TestSet, type="class")
confMatDecTree <- confusionMatrix(predictDecTree, TestSet$classe)
confMatDecTree

#plot matrix results
plot(confMatDecTree$table, col = confMatDecTree$byClass, 
     main = paste("Decision Tree - Accuracy =",
                  round(confMatDecTree$overall['Accuracy'], 4)))

#3. Applying the selected Model to the Test Data (Random Forest is selected because of higher accuracy)
predictTEST <- predict(modFitRandForest, newdata=testing)
predictTEST

```
